"""
    Credentials for accessing the Twitter API

    @author Alex Farrell
"""
# NOTE: THE TWITTER ACCOUNT IS NO LONGER ACTIVE. HOWEVER, TO AVOID DATA
#       EXPOSURE AS A SAFETY MEASURE, ALL CREDENTIAL TOKENS HAVE BEEN 
#       REMOVED. IF I WERE TO DEVELOP THIS PROJECT NOW, THESE WOULD BE 
#       IMPLEMENTED SEPARATELY ANYWAY IN A JSON.

CONSUMER_KEY     = "KEY_PLACEHOLDER"
CONSUMER_SECRET  = "SECRET_PLACEHOLDER"
ACCESS_KEY       = "AK_PLACEHOLDER"
ACCESS_SECRET    = "AS_PLACEHOLDER"
TWITTER_ID       = "ID_PLACEHOLDER"
PICASSO_USERNAME = 'USERNAME_PLACEHOLDER'
